version: '3.9'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamo/data:/home/dynamodblocal/data
    networks:
      - app-net

  db-init:
    build:
      context: .
      target: development
    container_name: dynamodb-init
    command: sh -c "chmod +x /app/scripts/init-db.sh && /app/scripts/init-db.sh"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    environment:
      AWS_REGION: "us-east-1"
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      TABLE_NAME: "Marketplace"
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
    depends_on:
      - dynamodb
    networks:
      - app-net
    restart: "no"

  api:
    build:
      context: .
      target: development
    container_name: marketplace-api
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    environment:
      AWS_REGION: "us-east-1"
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      TABLE_NAME: "Marketplace"
    depends_on:
      db-init:
        condition: service_completed_successfully
      dynamodb:
        condition: service_started
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  node_modules:
  pnpm-store:

